name: Node.js CI

on: [push]

strategy:
  matrix:
    node-version: ['10.x', '12.x' ,'14.x', '16.x', '18.x', '19.x', '20.x']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
