name: Node.js CI

on: [push]


jobs:
  build:

    strategy:
      matrix:
        node-version: ['16.x', '18.x', '19.x', '20.x', '22.x']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
